project_id = "wzquqhkshjxktcwdroqf"

[functions.validate-reservation]
verify_jwt = false

[functions.update-reservation-status]
verify_jwt = false

[functions.manage-expenses]
verify_jwt = false

[functions.das-notification-webhook]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

