// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfrswvmtmzizpjwmerye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmcnN3dm10bXppenBqd21lcnllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAwNzk3NTUsImV4cCI6MjA5NTY1NTc1NX0.QSOcXg7yVFLuuWT0kWXjMe8p7hEMM10-74R0MF3jSyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});